version: '3.8'

services:
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
      args:
        NODE_OPTIONS: "--max-old-space-size=8192"
    image: vpkebanii/frontend:latest

  backend:
    build:
      context: ./nodeapi
      dockerfile: Dockerfile
      args:
        NODE_OPTIONS: "--max-old-space-size=8192"
    image: vpkebanii/backend:latest
